alias py='python3'

alias g='git'
alias gb='git branch'
alias gs='git status'
alias gl='git log --oneline --graph'
alias gc='git commit -m $ARGS'
alias gf='git fetch origin'
alias gp='git pull'
alias ga='git add $ARGS'
